#include "/Engine/Private/Common.ush"
#include "/Engine/Private/RayTracing/RayTracingCommon.ush"

#include "/Engine/Private/Montecarlo.ush"
#include "/Engine/Private/PathTracing/Utilities/PathTracingRandomSequence.ush"



uint SamplesPerPixel;
float MaxRayDistance;
//RWTexture2D<float> RWAmbientOcclusionMaskUAV;
//RWTexture2D<float> RWAmbientOcclusionHitDistanceUAV;
DECLARE_SCALAR_ARRAY(int, RenderParams, 4);
RaytracingAccelerationStructure TLAS;
RWTexture2D<float4> OutputTexture;



void GenerateCosineNormalRay(
	float3 TranslatedWorldPosition,
	float3 WorldNormal,
	inout RandomSequence RandSequence,
	out float3 RayOrigin,
	out float3 RayDirection,
	out float RayTMin,
	out float RayTMax
)
{
	// Draw random variable
	float2 BufferSize = View.BufferSizeAndInvSize.xy;
	float2 RandSample = RandomSequence_GenerateSample2D(RandSequence);

	// Perform cosine-hemispherical sampling and convert to world-space
	float4 Direction_Tangent;
	#if 1
	{
		Direction_Tangent = CosineSampleHemisphereConcentric(RandSample);
		Direction_Tangent.w = Direction_Tangent.z;
	}
	#else
	{
		Direction_Tangent = CosineSampleHemisphere(RandSample);
	}
	#endif

	float3 Direction_World = TangentToWorld(Direction_Tangent.xyz, WorldNormal);

	RayOrigin = TranslatedWorldPosition;
	RayDirection = Direction_World;
	RayTMin = 1.0;
	RayTMax = MaxRayDistance;
}



RAY_TRACING_ENTRY_RAYGEN(MaterialViewRG)
{
	uint2 PixelCoord = DispatchRaysIndex().xy + View.ViewRectMin.xy;
	float2 PixelCenter = float2(PixelCoord) + 0.5;
	float2 ScreenUV = PixelCenter * View.BufferSizeAndInvSize.zw;
	float3 MissColor = float3(0.0, 0.0, 0.0);
	float3 CameraDir;
	float3 WorldPos;
	ReconstructTranslatedWorldPositionAndCameraDirectionFromDeviceZ(PixelCoord, 0.001, WorldPos, CameraDir);

	FRayDesc PrimaryRay;
	PrimaryRay.Origin = View.TranslatedWorldCameraOrigin;
	PrimaryRay.Direction = CameraDir;
	PrimaryRay.TMin = 0.0;
	PrimaryRay.TMax = 1e20;
	
	FPackedMaterialClosestHitPayload Payload = (FPackedMaterialClosestHitPayload)0;
	Payload.SetLumenPayload();
	FRayCone RayCone = (FRayCone)0; 
	RayCone.SpreadAngle = View.EyeToPixelSpreadAngle;

	TraceMaterialRayPacked(
		Payload,
		TLAS,
		RAY_FLAG_FORCE_OPAQUE,
		RAY_TRACING_MASK_OPAQUE,
		PrimaryRay,
		RayCone,
		false,
		true
		);
	
	float3 HitColor = float3(0.0, 0.0, 0.0);
	
	if (Payload.IsHit())
	{
		// Red = low freqs
		HitColor.x = log10( 1.0 + 9.0 * Payload.GetRoughness() );
		// Green = medium freqs
		HitColor.y = log10( 1.0 + 9.0 * Payload.GetMetallic() );
		// Blue = high freqs
		HitColor.z = log10( 1.0 + 9.0 * Payload.GetSpecular() );

		float diffuse = 0.5;
		float ambient = 0.5;

		// Diffuse
		if (GET_SCALAR_ARRAY_ELEMENT(RenderParams, 0))
		{
			diffuse = dot(View.DirectionalLightDirection, Payload.GetWorldNormal());
			
			if (diffuse >= 0.0)
			{
				diffuse = diffuse * 0.5;
			}
			else
			{
				diffuse = 0.0;
			}
		}

		// Ambient occlusion
		if (GET_SCALAR_ARRAY_ELEMENT(RenderParams, 1))
		{
			float hitNum = 0.0;
			float HitT = Payload.HitT;
			float3 HitWorldPos = PrimaryRay.Origin + (PrimaryRay.Direction * HitT);

			//float closestRayHitDistance = 10000.0;

			uint TimeSeed = View.StateFrameIndex;

			for (uint SampleIndex = 0; SampleIndex < SamplesPerPixel; ++SampleIndex)
			{
				FRayDesc Ray;

				RandomSequence RandSequence;
				RandomSequence_Initialize(RandSequence, PixelCoord, SampleIndex, TimeSeed, SamplesPerPixel);

				GenerateCosineNormalRay(HitWorldPos, Payload.GetWorldNormal(), RandSequence, Ray.Origin, Ray.Direction, Ray.TMin, Ray.TMax);

				FMinimalPayload MinimalPayload = TraceVisibilityRay(
					TLAS,
					RAY_FLAG_FORCE_OPAQUE,
					RAY_TRACING_MASK_OPAQUE,
					Ray);
				
				
				if (MinimalPayload.IsHit())
				{
					hitNum += 1.0;
					//closestRayHitDistance = min(closestRayHitDistance, MinimalPayload.HitT);

					// Linear scaling for occlusion (each intersection has constant occluding factor)
					if (GET_SCALAR_ARRAY_ELEMENT(RenderParams, 3) == 0)
					{
						ambient -= 0.5 / SamplesPerPixel;	
					}

					// Distance based scaling for occlusion
					if (GET_SCALAR_ARRAY_ELEMENT(RenderParams, 3) == 3)
					{
						ambient -= 0.5 / SamplesPerPixel * ( 1 - 1 / MaxRayDistance * MinimalPayload.HitT );
					}
				}
			}

			// Factorial scaling for occlusion (each intersection has increasing occluding factor)
			if (GET_SCALAR_ARRAY_ELEMENT(RenderParams, 3) == 1)
			{
				ambient -= 0.5 / ((SamplesPerPixel + 1) * SamplesPerPixel / 2) * ((hitNum + 1) * hitNum / 2);
			}

			// Exponential scaling for occlusion (each intersection has increasing occluding factor)
			if (GET_SCALAR_ARRAY_ELEMENT(RenderParams, 3) == 2)
			{
				ambient -= 0.5 / (SamplesPerPixel * SamplesPerPixel) * (hitNum * hitNum);
			}
			
			//RWAmbientOcclusionMaskUAV[PixelCoord] = ambient;
			//RWAmbientOcclusionHitDistanceUAV[PixelCoord] = closestRayHitDistance == 10000.0 ? -1.0 : closestRayHitDistance;
		}
		/*
		else
		{
			RWAmbientOcclusionMaskUAV[PixelCoord] = 0.0;
			RWAmbientOcclusionHitDistanceUAV[PixelCoord] = 1.0;	
		}
		*/
		
		// Shadow
		if (GET_SCALAR_ARRAY_ELEMENT(RenderParams, 2))
		{
			float HitT = Payload.HitT;
			float3 HitWorldPos = PrimaryRay.Origin + (PrimaryRay.Direction * HitT);
			FPackedMaterialClosestHitPayload ShadowPayload = (FPackedMaterialClosestHitPayload)0;
			FRayDesc ShadowRay;
			ShadowRay.Origin = HitWorldPos;
			ShadowRay.Direction = View.DirectionalLightDirection;
			ShadowRay.TMin = 1.0;
			ShadowRay.TMax = 1e20;
			
			TraceMaterialRayPacked(
				ShadowPayload,
				TLAS,
				RAY_FLAG_FORCE_OPAQUE,
				RAY_TRACING_MASK_OPAQUE,
				ShadowRay,
				RayCone,
				false,
				true
				);
			if (ShadowPayload.IsHit())
			{
				diffuse = 0.0;
			}
		}

		OutputTexture[DispatchRaysIndex().xy] = float4(HitColor * (diffuse + ambient), 1.0);
		return;
	}

	OutputTexture[DispatchRaysIndex().xy] = float4(MissColor, 1.0);
}